devices: 1
epochs: 300
sr: 16000
download: False
segment: 10

defaults:  # TODO: make moisedb matches with musdb format
    - dataset: moisedb
    - model: UNet

        
dataloader:
    train:
        batch_size: 16
        num_workers: 40
        shuffle: True
        pin_memory: True
    val:
        batch_size: 16
        num_workers: 4
        shuffle: False
        pin_memory: True
    test:
        batch_size: 16
        num_workers: 4
        shuffle: False
        pin_memory: True        

        

trainer:
    devices: ${devices}
    max_epochs: ${epochs}
    check_val_every_n_epoch: 30
    log_every_n_steps: 100 
    
# Check https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/    
hydra:
    job:
        chdir: True