devices: 1
epochs: 1000
sr: 16000
data_root: '/root/dataset/mss/moisesdb23_labelnoise_v1.0_16k_stereo'
model_name: 'Conv128'
checkpoint_path: './conv128_epoch696.ckpt'

defaults:    
    - dataset: musdb
        
dataloader:
    test:
        batch_size: 16
        num_workers: 40
        shuffle: False
        pin_memory: True

trainer:
    devices: ${devices}
    max_epochs: ${epochs}
    check_val_every_n_epoch: 30
    
# Check https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/    
hydra:
    job:
        chdir: True