name: 'Moisesdb23'
data_root: '/root/dataset/mss/moisesdb23_labelnoise_v1.0_16k_stereo'

train:
    root: ${dataset.data_root} 
    segment: ${segment}
    samplerate: ${sr}
    
val:
    root: ${dataset.data_root} 
    segment: ${segment}
    samplerate: ${sr}